removed cypress
0chain/actions pull request #157
Opened 2023-05-02 04:55 UTC by Manali-Jain-squareops

2023-05-02 20:46 UTC, stewartie4 commented
adding @cnlangzi who added the tests
I agree, they don't belong with the backend tests, these guys should run on the frontend repos only right @cnlangzi ?

2023-05-02 20:46 UTC, stewartie4 approved these changes

2023-05-03 20:20 UTC, stewartie4 requested changes
After some reflection, maybe this is a more prudent approach? https://github.com/0chain/actions/pull/162

2023-05-03 20:23 UTC, Kishan-Dhakan commented
Closing, handled in https://github.com/0chain/actions/pull/162

2023-05-03 20:23 UTC, closed without merging